language: php

env:
  global:
    - COMPOSER_MEMORY_LIMIT=4G
    - SYMFONY_REQUIRE=>=3.4

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6

install:
  - composer global require rubenrua/symfony-clean-tags-composer-plugin
  - composer install

script: vendor/bin/phpunit
